### ISSUE TITLE
Exception inside handler, but no try/catch in main

### ISSUE THREAD

**Issue by schorsch1976** [liancheng/amy#10]
In https://github.com/liancheng/amy/blob/master/example/async_execute.cpp in the utils.cpp:check_error() function you throw an exception if there has been any error. 

Boost asio states in 
http://www.boost.org/doc/libs/1_61_0/boost/asio/io_service.hpp

```
 * @par Effect of exceptions thrown from handlers
 *
 * If an exception is thrown from a handler, the exception is allowed to
 * propagate through the throwing thread's invocation of run(), run_one(),
 * poll() or poll_one(). No other threads that are calling any of these
 * functions are affected. It is then the responsibility of the application to
 * catch the exception.
 *
 * After the exception has been caught, the run(), run_one(), poll() or
 * poll_one() call may be restarted @em without the need for an intervening
 * call to reset(). This allows the thread to rejoin the io_service object's
 * thread pool without impacting any other threads in the pool.
```

So, in main, there should be a try/catch handler for this exception. The other issue is, when there are multiple threads calling run(), there needs to be an handler for each run() function of each thread.

In the examples of boost asio, this gets handled, that the shared pointers get out of scope and not further kept alive. Read: The new async operations dont get restarted. They Pop pot of the dispatch queue and get cleaned up.

**Comment by schorsch1976** [comment]
I forgot: asio provides an example of this a few lines below the above comment:

 * For example:
 *
 * @code
 * boost::asio::io_service io_service;
 * ...
 * for (;;)
 * {
 *   try
 *   {
 *     io_service.run();
 *     break; // run() exited normally
 *   }
 *   catch (my_exception& e)
 *   {
 *     // Deal with exception as appropriate.
 *   }
 * }
 * @endcode

**Comment by liancheng** [comment]
@schorsch1976 Thanks! I was just being lazy and skipped exception handling in examples :) Addressing this issue with PR #11.
