### ISSUE TITLE
Travis build is failing because string_view is not available

### ISSUE THREAD

**Issue by liancheng** [liancheng/amy#18]
It seems that `string_view` is not available in the Boost version shipped with Ubuntu Trusty.

This should be relatively easy to fix by downloading and installing a more recent version of Boost instead of using the version shipped with Ubuntu Trusty. However, I'd propose to remove `string_view` entirely from Amy or at least make it configurable at build time.

While refactoring Amy in late 2016, one rule of thumb of mine is to reduce as many dependencies as possible to remove unnecessary burdens from the end-users. In the case of `string_view`, for Boost users, it is only available in newer versions of Boost, and for non-Boost users, it is only available since C++ 17, which is still quite new. On the other hand, I don't see a lot of benefits in introducing `string_view`. In short, it blocks many potential users who (have to) stick with older libraries/toolchains without a good reason.

**Comment by hhggit** [comment]
Using `std::string`  will implicitly copy all the sql results once, I think this overhead should be done explicitly by the the users not by the lib. 

The PR#19  expose the sql field's pointer and length, leave it to user to decide how to deal with the `value_cast` (I perfer this way, as some of other lib may already provide some effective way to convert strings)

**Comment by liancheng** [comment]
@hhggit I like your new approach in #19 :)
