### ISSUE TITLE
Migrate to CMake

### ISSUE THREAD

**Issue by liancheng** [liancheng/amy#5]
Mostly for a better ecosystem. Especially, CLion has built-in CMake support.

**Comment by bluealert** [comment]
https://github.com/bluealert/amy-cmake

我把您的代码改成cmake构建了。在macOS 10.13.1上编译完全通过。把mysql_service移到amy/detail里面了，把mysql_service.cpp删去了。也就是说，现在amy-cmake是一个纯头文件库了。

**Comment by liancheng** [comment]
@bluealert Sorry for the late reply and thanks for your efforts! Would you like to send a pull request for your CMake changes?

I didn't quite get the `mysql_service.cpp` part, though. I don't think that file ever existed in Amy and Amy was designed to be a header only library from the very beginning.

BTW, it would be great if you can leave messages here in English so that our discussions can be more widely accessible! 🌏 🌍 🌎

**Comment by bluealert** [comment]
I have changed the code too much. For example, I only support Boost.Asio, not support vanilla Asio. I also remove `SConstruct` file. To merge the code properly is too difficult? I think you do the support to CMake yourself would be less work?

**Comment by liancheng** [comment]
Ah, I see, that's why you made a whole new repository instead of forking Amy. Yea, borrowing code from your repo seems to be easier. I will probably keep both SCons and CMake for a while before having all the options ported to CMake. Thanks for the explanation!

**Comment by hhggit** [comment]
fixed in #17
